---
- name: Create a custom Docker network
  shell: "docker network create {{ nginx_docker_network }} || echo 'Network already exists'"
  changed_when: false
  tags:
    - create-network

- name: Pull Nginx Docker image
  shell: "docker pull nginx:latest"
  tags:
    - pull-nginx-image

- name: Copier la configuration Nginx
  ansible.builtin.copy:
    src: nginx.conf
    dest: /tmp/nginx.conf
    owner: root
    group: root
    mode: '0644'
  tags:
    - copy-nginx-config

- name: Stop existing Nginx container
  shell: "docker stop nginx || echo 'Container not running'"
  changed_when: false
  tags:
    - stop-nginx-container

- name: Remove existing Nginx container
  shell: "docker rm nginx || echo 'Container does not exist'"
  changed_when: false
  tags:
    - remove-nginx-container

- name: Run Nginx container
  shell: "docker run -d --name nginx -p 80:80 --network {{ nginx_docker_network }} -v /tmp/nginx.conf:/etc/nginx/nginx.conf:ro nginx:latest"
  tags:
    - run-nginx-container
